### ISSUE TITLE
Few questions about track angle and turn percent

### ISSUE THREAD

**Issue by V1ss** [sergionr2/RacingRobot#9]
Hello,

Thank you for sharing your whole project. I am trying to make it myself, but I have a few questions that I can’t understand, maybe you would have the time to explain them to me.

When you’re calculating track_angle, where did you got the formula arctan(1/m)?

Where did you got the formula for turn_percent = (diff_angle / max_angle) *100?

Why did you chose ref_angle -90 degrees and ref_angle 45 degrees?

Sorry if these questions sound dumb to you, I am just trying to understand where these calculations are coming from.

I would be very grateful if you could answer them.

Have a nice day!

**Comment by araffin** [comment]
Hello,

>When you’re calculating track_angle, where did you got the formula arctan(1/m)?

this explanation is right [above](https://github.com/sergionr2/RacingRobot/blob/master/image_processing/image_processing.py#L43): instead of fitting `y = m * x + b`, we fit `x = 1/m * y - b /m` because it leads to less instabilities. (where x and y are the coordinate of the image). Because at the end, we want the angle of the turn, we take the arctan of the slope which is 1 / m.

>Where did you got the formula for turn_percent = (diff_angle / max_angle) *100?

This is just normalization. The estimation of the line curvature will saturate if `diff_angle > max_angle`. 
the idea is: at 0% we are in straight line, at 100% we have a sharp turn. And we don't make a difference between a sharp turn (== MAX_ANGLE) and a very sharp turn (> MAX_ANGLE).

>Why did you chose ref_angle -90 degrees and ref_angle 45 degrees?

The ref angle is only used to express the angle in the right coordinate system (and depends on how the image is represented).
The second value is the `MAX_ANGLE` which says what is the maximum turn we expect (cf previous question).

**Comment by V1ss** [comment]
Thank you very for your answers, everything now is clear. Just you say that for counting the angle of the turn, we take arctan of the slope 1/m.  But on wikipedia I find that the angle is arctan of just m. https://en.wikipedia.org/wiki/Slope 

Which one is correct? Thanks

**Comment by araffin** [comment]
The two are corrects, please read carefully my first sentence: I have changed slightly the problem, instead of searching the slope of y = f(x), I search the slope of x = f(y) (which is equivalent for a line expect for corner cases like y = constant or x = constant)

**Comment by V1ss** [comment]
Oh I see know, thank you very much!
